#include <18F46K22.h>
#device ADC=10

#FUSES NOWDT,NOPROTECT,NOLVP HSM,NOPLLEN,NOFCMEN,PUT,BROWNOUT_SW,BORV22,CCP2C1,NOPBADEN,CCP3E0,NOHFOFST,TIMER3C0
#FUSES CCP2D2,MCLR,STVREN,NOXINST,NODEBUG,NOCPB,NOCPD,NOWRT,NOWRTC,NOWRTB,NOWRTD,NOEBTR,NOEBTRB                  

#use delay(crystal=8000000,restart_wdt)
#use I2C(master, sda=PIN_C4, scl=PIN_C3, FORCE_HW)  

